import { createRequire } from 'module';

import ANSWERS from './answers.mjs';

export const WORD_LENGTH = 5;

const FIVE_LETTERS = new RegExp(`^[a-z]{${WORD_LENGTH}}$`);

// Answers come from a curated pool of words the community will recognise,
// regenerated by operations/patching/buildCoopdleWords.mjs. Guesses are not
// held to it: anything in the dictionary is fair play.
const answerSet = new Set(ANSWERS);

// The dictionary is ~275k words of JSON, so it is loaded on first use rather
// than at boot: Cooper only needs it when a Coopdle actually runs.
let loading = null;
let guessable = null;

const load = async () => {
    const require = createRequire(import.meta.url);

    // Only the five letter words are ever asked about, and keeping those alone
    // drops the dictionary from 275k entries to 13k.
    guessable = new Set(require('an-array-of-english-words').filter(word => FIVE_LETTERS.test(word)));

    return guessable;
};

// Resolves once the dictionary is usable, loading it if required.
export const ready = () => loading || (loading = load());

export const answerCount = () => ANSWERS.length;

// The answer is chosen by offset into the pool, so the caller controls the roll.
export const wordAt = offset => ANSWERS[offset % ANSWERS.length];

export const isValidGuess = word => {
    const candidate = String(word).toLowerCase();
    if (!FIVE_LETTERS.test(candidate)) return false;
    return answerSet.has(candidate) || guessable.has(candidate);
};
