/**
 * Regenerates the Coopdle answer pool: operations/minigames/small/coopdle/answers.mjs
 *
 *     node ./operations/patching/buildCoopdleWords.mjs
 *
 * Guesses are checked against the whole of an-array-of-english-words at
 * runtime - if it is in the dictionary it is fair play. This only decides what
 * Cooper is allowed to *pick* as a secret word, which is a higher bar: the
 * board is shared and the answer has to be crackable between everyone. An
 * answer can be obscure, it just has to be a word people actually write, so
 * the only things dropped are proper nouns, inflections, and the couple of
 * thousand dictionary entries that appear nowhere in real usage.
 *
 * Needs network access, it pulls the two lists below.
 */

import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const words = require('an-array-of-english-words');

const WORD_LENGTH = 5;

// Word counts over the Google Web Trillion Word Corpus. Only used as proof
// that a word gets written down: dictionaries carry dialect and Scrabble
// entries like AALII and SMOWT that do not appear in it even once.
const FREQUENCY_URL = 'https://norvig.com/ngrams/count_1w.txt';

// The dictionary is all lowercase, so PARIS and HONDA look like ordinary words
// in it. This Hunspell dictionary keeps its capitals, which is enough to tell
// the proper nouns apart.
const HUNSPELL_URL = 'https://raw.githubusercontent.com/wooorm/dictionaries/main/dictionaries/en/index.dic';

const fetchText = async url => {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url} responded ${response.status}`);
    return await response.text();
};

const build = async () => {
    const dictionary = new Set(words);
    const fiveLetter = new Set(words.filter(word => new RegExp(`^[a-z]{${WORD_LENGTH}}$`).test(word)));

    const [frequencyList, hunspell] = await Promise.all([
        fetchText(FREQUENCY_URL),
        fetchText(HUNSPELL_URL)
    ]);

    const frequencies = frequencyList.split('\n');

    // Headwords of the Hunspell dictionary, capitals and all.
    const headwords = hunspell.split('\n').map(line => line.split('/')[0].trim());
    const capitalised = new Set(headwords.filter(word => /^[A-Z]/.test(word)).map(word => word.toLowerCase()));
    const lowercase = new Set(headwords.filter(word => /^[a-z]/.test(word)));

    // A name and nothing else: PARIS is out, but DRAKE and WELSH stay because
    // they are also words in their own right.
    const isProperNoun = word => capitalised.has(word) && !lowercase.has(word);

    // An inflection rather than a word in its own right: "moths", "asked",
    // "going". The stem gives the whole thing away, so the guesser is left
    // picking a random verb rather than solving anything. Stems are checked
    // against the dictionary, so words that only look inflected ("brass",
    // "chaos", "creed") survive.
    const stems = word => {
        // "ss" is never a plural ending, which keeps BRASS, GUESS and GLOSS.
        if (word.endsWith('s') && !word.endsWith('ss')) return [word.slice(0, -1)];
        if (word.endsWith('ed')) return [word.slice(0, -1), word.slice(0, -2)];
        if (word.endsWith('ing')) return [word.slice(0, -3)];
        return [];
    };

    const isInflection = word => stems(word).some(stem => dictionary.has(stem));

    const used = new Set(frequencies.map(line => line.split('\t')[0]));

    const answers = [...fiveLetter]
        .filter(word => used.has(word) && !isProperNoun(word) && !isInflection(word))
        .sort();

    const target = path.join(
        path.dirname(fileURLToPath(import.meta.url)),
        '../minigames/small/coopdle/answers.mjs'
    );

    const rows = [];
    for (let index = 0; index < answers.length; index += 10)
        rows.push(`    ${answers.slice(index, index + 10).map(word => `'${word}'`).join(', ')}`);

    fs.writeFileSync(target, [
        '// Generated by operations/patching/buildCoopdleWords.mjs - do not edit by hand.',
        '//',
        `// ${answers.length} five letter English words a Coopdle answer can be drawn from:`,
        '// the dictionary less proper nouns, inflections and entries nobody writes.',
        '// Guesses are not limited to these, they are checked against the full',
        '// dictionary.',
        'export default [',
        rows.join(',\n'),
        '];',
        ''
    ].join('\n'));

    console.log(`Wrote ${answers.length} answers to ${target}`);
};

build().catch(error => {
    console.error(error);
    process.exit(1);
});
